# -*- coding: utf-8 -*-
"""Sensei-Assistente-de-apredizagem

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rr7dpsLUj_f6K763qLLdIm9mCaA_C9tS
"""

!pip install google-generativeai

!pip install -q google-adk

!pip install streamlit -q

from google.colab import userdata
os.environ["GOOGLE_API_KEY"] = userdata.get('GOOGLE_API_KEY')

!wget -q -O - ipv4.icanhazip.com

! streamlit run app.py & npx localtunnel --port 8501